model:
  base_learning_rate: 4.5e-6
  target: models.autoencoder.AutoEncoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 16
    lossconfig:
      target: utils.losses.LPIPSWithDiscriminator
      params:
        disc_start: 501
        kl_weight: 1e-6
        disc_weight: 0.5
    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ 16 ]
      dropout: 0.0

data:
  target: data.MRIDataModule.MRIDataModule
  params:
    dataset_path: '../DB_IA-Gen-Med-Im'
    manifest_filename: 'MRI_dataset_autoencoder.csv'
    task: 'autoencoder'
    seed: 23
    num_workers: 4
    batch_size: 6
    crop_size: 256
    train_val_test_split: [0.1, 0.05, 0.85]

lightning:
  trainer:
    benchmark: True
    accelerator: auto  # cpu, gpu, tpu, hpu or auto
    devices: auto
    strategy: auto
    #accumulate_grad_batches: 2