name: IA-Gen-Med-Im
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - pip=24.0
  - cudatoolkit=12.1
  - pytorch=2.3.
  - torchvision=0.18.1
  - numpy=1.26.3
  - pip:
      - lightning==2.3.0
      - torcheval==0.0.7
      - torchinfo==1.8.0
      - tqdm==4.66.4
      - einops==0.8.0
      - matplotlib==3.9.0
      - pandas==2.2.2
      - seaborn==0.13.2
      - nibabel==5.2.1
      - omegaconf==2.3.0
      - tensorboard==2.17.0
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers